[package]
name = "ratatetris"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
assert_no_alloc = "1.1.2"
color-eyre = "0.6.5"
cpal = "0.17.1"
crossterm = "0.29.0"
fundsp = "0.23.0"
midly = "0.5.3"
rand = "0.9.2"
ratatui = "0.30.0"
rustysynth = "1.3.6"
